from copy import deepcopy
import sys

FINAL_CANONICAL_CONFIGURATION = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 0]]

class ShortSequence_Solver15:
    initial_state = None;
    explored_set = None;
    is_solvable = None;
    moves = None;
    r = None;
    c = None;
    
    # Parameterized constructor reads input file and checks for solvability.
    def __init__(self, filename):
        self.read_check_input_file(filename);
        self.explored_set = [];
        self.moves = [];
    
    # Reads the puzzle to a 2-D matrix and checks if puzzle is solvable   
    def read_check_input_file(self, filename):
        with open(filename, 'r') as f:
            self.initial_state = [[int(j) for j in i] for i in [line.split() for line in f]]
            
        self.is_solvable = self.is_solvable(self.initial_state);
    
    # Heuristic ==> Manhattan distance    
    # https://stackoverflow.com/questions/12526792/manhattan-distance-in-a   
    def manhattan_distance(self, successor_state):
        manhattanDistanceSum = 0;
        for x in range(4):
            for y in range(4):
                value = successor_state[x][y];
                if (value != 0):
                    targetX = (value - 1) // 4;
                    targetY = (value - 1) % 4;
                    dx = x - targetX;
                    dy = y - targetY;
                    manhattanDistanceSum += abs(dx) + abs(dy)
                    
        return manhattanDistanceSum;
    
    # Successor states generated by moving tiles by one, two or three positions to the top, bottom, left or right as appropriate
    def successors(self, tiles):
        successor_states = []
        moves = []
        for i in range(4):
            for j in range(4):
                if(i == self.r and j == self.c):
                    #move up by one tile
                    if(i > 0):
                        tiles[i][j], tiles[i-1][j] = tiles[i-1][j], tiles[i][j];  
                        successor_states.append(deepcopy(tiles))
                        tiles[i][j], tiles[i-1][j] = tiles[i-1][j], tiles[i][j];
                        move = "D" + str(self.r + 1); # sequence of moves string builder
                        moves.append(move) # sequence of moves list
                    #move up by one tile
                        
                    #move down by one tile
                    if(i < 3):
                        tiles[i][j], tiles[i+1][j] = tiles[i+1][j], tiles[i][j]
                        successor_states.append(deepcopy(tiles))
                        tiles[i][j], tiles[i+1][j] = tiles[i+1][j], tiles[i][j]
                        move = "U" + str(self.r + 1);
                        moves.append(move)
                    #move down by one tile
                        
                    #move left by one tile
                    if(j > 0):
                        tiles[i][j], tiles[i][j-1] = tiles[i][j-1], tiles[i][j];  
                        successor_states.append(deepcopy(tiles))
                        tiles[i][j], tiles[i][j-1] = tiles[i][j-1], tiles[i][j];  
                        move = "R" + str(self.c + 1);
                        moves.append(move)
                    #move left by one tile
                        
                    #move right by one tile
                    if(j < 3):
                        tiles[i][j], tiles[i][j+1] = tiles[i][j+1], tiles[i][j]
                        successor_states.append(deepcopy(tiles))
                        tiles[i][j], tiles[i][j+1] = tiles[i][j+1], tiles[i][j]
                        move = "L" + str(self.c + 1);
                        moves.append(move)
                    #move right by one tile

        return [successor_states, moves];
    
    # Checks whether current state is tje goal state or not.
    def is_goal(self, successor_state):
        for i in range(len(successor_state)):
            for j in range(len(successor_state[0])):
                if(successor_state[i][j] != FINAL_CANONICAL_CONFIGURATION[i][j]):
                    return False;
                
        return True;
    
    # http://www.geeksforgeeks.org/check-instance-15-puzzle-solvable/
    # A utility function to count inversions in given tile(1-D)
    def get_inv_count(self, tile):
        inv_count = 0;
        for i in range(15):
            for j in range(i + 1, 16):
                #count pairs(i, j) such that i appears before j, but i > j.
                if (tile[j] and tile[i] and tile[i] > tile[j]):
                    inv_count += 1;
                    
        return inv_count;
    
    # http://www.geeksforgeeks.org/check-instance-15-puzzle-solvable/
    # find Position of blank from bottom starting from bottom-right corner of matrix
    def find_X_position(self, tile):
        for i in range(3, -1, -1):
            for j in range(3, -1, -1):
                if (tile[i][j] == 0):
                    return 4 - i;
                
    # http://www.geeksforgeeks.org/check-instance-15-puzzle-solvable/
    # This function returns true if given instance of 15 puzzle is solvable.
    def is_solvable(self, tile):
        #Count inversions in given puzzle
        tile_1D = [0 for elem in range(16)];
        for i in range(4):
            for j in range(4):
                tile_1D[4 * i + j] = tile[i][j]
                
        inv_count = self.get_inv_count(tile_1D);
     
        #If grid is odd, return true if inversion count is even.
        if (4 & 1):
            return not (inv_count & 1);
     
        else: #grid is even
            pos = self.find_X_position(tile);
            if(pos & 1):
                return not (inv_count & 1);
            else:
                return inv_count & 1;
    
    # Invokes the A-star algorithm to solve the 15 puzzle if it is solvable.
    def solve(self):
        if(self.is_solvable):
            return self.solve_A_star(self.initial_state, self.explored_set, self.moves, g_cost = 1);
    
    # A-star search finds the best promising state after each step based on min 'f'(g + h) value till the goal state is reached.    
    def solve_A_star(self, state, explored_state, moves, g_cost):
        if(self.is_goal(state)):
            return 0;
        # find row and column number of 'blank' tile.
        self.r, self.c = [(index, row.index(0)) for index, row in enumerate(state) if 0 in row][0]
        
        tmp = []
        successors = self.successors(state)[0];
        successors_moves = self.successors(state)[1];
        
        for cnt, s in enumerate(successors):
            if(self.is_goal(s)):
                explored_state.append(s);
                moves.append(successors_moves[cnt]);
                return 0;

            h_cost = self.manhattan_distance(s);
            tmp.append((s, successors_moves[cnt], g_cost + h_cost))
        
        # https://stackoverflow.com/questions/10695139/sort-a-list-of-tuples-by-2nd-item-integer-value
        # next_promising_state is chosen based on min f_cost = g_cost + h_cost
        next_promising_state = sorted(tmp, key=lambda x: x[2])[0][0]
        explored_state.append(next_promising_state);
        moves.append(sorted(tmp, key=lambda x: x[2])[0][1]);
        # https://algorithmsinsight.wordpress.com/graph-theory-2/a-star-in-general/implementing-a-star-to-solve-n-puzzle/
        g_cost += 1;
        
        # recursively iterate through promising states to reach the goal state
        self.solve_A_star(next_promising_state, explored_state, moves, g_cost) 
        
    #Returns a string that represents the output of the program.
    def __str__(self):
        if(self.is_solvable):
            if(self.moves != []):
                output_str = "";
                output_str += "\n".join(str(row) for row in [self.initial_state] + self.explored_set)
                output_str += "\n\nSEQUENCE OF MOVES:\n" +  " ".join(self.moves)
                return output_str;
            else:
                return ("Input puzzle is in goal state.")
        else:
            return ("PUZZLE NOT SOLVABLE");

def main():
    filename =  "puzzle.txt"
    s = ShortSequence_Solver15(filename);
    s.solve()
    print(str(s));
    
if(__name__ == "__main__"):
    main();
